server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loogodamner?serverTimezone=UTC&characterEncoding=utf-8 
    username: root
    password: bbb961122
  thymeleaf:
    cache: false
