spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  profiles: loogodamner2
server:
  port: 8762
eureka:  instance:    hostname: loogodamner2
  client:
    service-url:      defaultZone: http://loogodamner1:8761/eureka/