server:
  port: 8011
spring:
  application:
    name: microservice-consumer-movie
microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#若不想注册到eureka server
#spring.cloud.service-registry.auto-registration.enabled=false